### PR TITLE
[filament_view] Fixes shadow artifacts on decals with transparency

### LINKED ISSUE #32: Transparency artifacts on quads with large alpha=0 areas
When lit by a point light, quads with large transparent areas show weird artifacting:

Image

- workspace-automation ref: https://github.com/meta-flutter/workspace-automation/commit/55ab7fcbdd6b4ddc72b6b3ccb32422f20117f584
- playx-3d-scene ref: https://github.com/meta-flutter/playx-3d-scene/commit/db5e4bb519b4727eeee567be368b2f0c1f8bb5f4
- filament_view ref: https://github.com/toyota-connected/ivi-homescreen-plugins/commit/3c42bddcea7beba16d073ff308af2929f023f73d
- Platform: Linux amd64
- OS: Fedora 41
- GPU: Intel Mesa graphics

### PR DESCRIPTION
**Pull request by kerberjg**
Fixes meta-flutter/playx-3d-scene#32

> Note for the future: If you're reading this, **avoid VSF shadows** - they're faster but they cause weird artifacts on decals with large transparent areas. **No issues with PCF, DPCF, PCSS**, all have been tested

Before: 
Screenshot From 2025-02-25 00-17-17

After:
Screenshot From 2025-02-24 23-51-01

### CODE REVIEW

File: plugins/filament_view/core/scene/view_target.cc [hunk 1]
```diff
@@ -236,16 +236,21 @@ void ViewTarget::vChangeQualitySettings(
...
-      settings.shadowType = filament::View::ShadowType::VSM;
-      settings.vsmShadowOptions = {.anisotropy = 0,
-                                   .mipmapping = false,
-                                   .msaaSamples = 1,
-                                   .highPrecision = false,
-                                   .minVarianceScale = 0.5f,
-                                   .lightBleedReduction = 0.15f};
+      settings.dynamicLighting.zLightFar = 50.0f;
+      settings.shadowType = filament::View::ShadowType::PCF;
+      // fview_->setSoftShadowOptions({
```
Comment (jwinarske) [inline plugins/filament_view/core/scene/view_target.cc]: @kerberjg The commented out code should be removed

File: plugins/filament_view/core/scene/view_target.cc [hunk 2]
```diff
@@ -255,19 +260,24 @@ void ViewTarget::vChangeQualitySettings(
...
+      settings.dynamicLighting.zLightNear = 0.01f;
       settings.dynamicLighting.zLightFar = 100.0f;
       settings.shadowType = filament::View::ShadowType::PCF;
-      settings.vsmShadowOptions = {.anisotropy = 0,
-                                   .mipmapping = true,
-                                   .msaaSamples = 2,
-                                   .highPrecision = false,
-                                   .minVarianceScale = 0.4f,
-                                   .lightBleedReduction = 0.2f};
+      // fview_->setSoftShadowOptions({
```
Comment (jwinarske) [inline plugins/filament_view/core/scene/view_target.cc]: @kerberjg The commented out code should be removed

File: plugins/filament_view/core/scene/view_target.cc [hunk 3]
```diff
@@ -279,15 +289,13 @@ void ViewTarget::vChangeQualitySettings(
...
+      settings.dynamicLighting.zLightNear = 0.01f;
+      settings.dynamicLighting.zLightFar = 250.0f;
       settings.shadowType = filament::View::ShadowType::PCF;
-      // settings.vsmShadowOptions = {.anisotropy = 1,
-      //                              .mipmapping = true,
-      //                              .msaaSamples = 4,
-      //                              .highPrecision = false,
-      //                              .minVarianceScale = 0.3f,
-      //                              .lightBleedReduction = 0.3f};
+      // fview_->setSoftShadowOptions({
```
Comment (jwinarske) [inline plugins/filament_view/core/scene/view_target.cc]: @kerberjg The commented out code should be removed

File: plugins/filament_view/core/scene/view_target.cc [hunk 4]
```diff
@@ -306,15 +314,13 @@ void ViewTarget::vChangeQualitySettings(
...
+      settings.dynamicLighting.zLightNear = 0.01f;
       settings.dynamicLighting.zLightFar = 500.0f;
-      settings.shadowType = filament::View::ShadowType::DPCF;
-      // settings.vsmShadowOptions = {.anisotropy = 2,
-      //                              .mipmapping = true,
-      //                              .msaaSamples = 4,
-      //                              .highPrecision = true,
-      //                              .minVarianceScale = 0.2f,
-      //                              .lightBleedReduction = 0.4f};
+      settings.shadowType = filament::View::ShadowType::PCF;
```
Comment (jwinarske) [inline plugins/filament_view/core/scene/view_target.cc:293]: @kerberjg The commented out code should be removed

File: plugins/filament_view/core/scene/view_target.cc [hunk 5]
```diff
@@ -337,13 +343,11 @@ void ViewTarget::vChangeQualitySettings(
...
       settings.renderQuality = {.hdrColorBuffer =
                                     filament::View::QualityLevel::HIGH};
-      settings.shadowType = filament::View::ShadowType::VSM;
-      settings.vsmShadowOptions = {.anisotropy = 0,
-                                   .mipmapping = false,
-                                   .msaaSamples = 1,
-                                   .highPrecision = false,
-                                   .minVarianceScale = 0.5f,
-                                   .lightBleedReduction = 0.15f};
+      settings.shadowType = filament::View::ShadowType::PCF;
```
Comment (jwinarske) [inline plugins/filament_view/core/scene/view_target.cc:316]: @kerberjg The commented out code should be removed

**Review by jwinarske — CHANGES_REQUESTED** [review]

**Comment by jwinarske** [comment]
cc @tcadanklefsen

**Review by jwinarske — APPROVED** [review]
